apiVersion: v1
kind: Pod
metadata:
  generation: 1
  name: elephant
  namespace: default
  resourceVersion: "1011"
  uid: 9a905778-e738-4e2c-adc5-57743bbbadf1
spec:
  containers:
  - args:
    - --vm
    - "1"
    - --vm-bytes
    - 15M
    - --vm-hang
    - "1"
    command:
    - stress
    image: polinux/stress
    imagePullPolicy: Always
    name: mem-stress
    resources:
      limits:
        memory: 20Mi
      requests:
        memory: 5Mi
