apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: blu-deploy
  name: blu-deploy
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node
            operator: In
            values:
            - asif 
  replicas: 1
  selector:
    matchLabels:
      app: blu-deploy
  template:
    metadata:
      labels:
        app: blu-deploy
    spec:
      containers:
      - image: nginx
        name: nginx
